spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/spring
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
      hibernate:
          ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          #show-sql: true

logging.level:
    org.hibernate.SQL: INFO
    #org.hibernate.type.descriptor.sql.BasicBinder: trace

